# 로컬 환경
spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: ${/pinme/rds-url}
    username: ${/pinme/rds-id}
    password: ${/pinme/rds-pw}

  data:
    mongodb:
      uri: ${/pinme/mongodb-url}
      database: ${/pinme/mongodb-database}

  # redis
  redis:
    host: ${/pinme/redis-host}
    port: 6379

  jackson:
    serialization:
      fail-on-empty-beans: false

  # google 메일 발송
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${/pinme/google-id}
    password: ${/pinme/google-pw}
    properties:
      debug: true
      mail.smtp:
        auth: true
        starttls:
          enable: true

  # image upload limit
  servlet.multipart:
    maxFileSize: 10MB
    maxRequestSize: 10MB

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# paramter store
awsParameterStorePropertySource:
  enabled: true

# s3
cloud:
  aws:
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ${/pinme/access-key}
      secret-key: ${/pinme/secret-key}
      instance-profile: true
    s3.bucket: ${/pinme/s3-bucket}


# OAuth
OAuth2:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${/pinme/google-oauth2-client-id}
    client-secret: ${/pinme/google-oauth2-client-secret}
    callback-url: ${/pinme/google-oauth2-callback-url}
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile


# swaggerdoc
springdoc:
  version: v1.0.0
  packages-to-scan: com.gigajet.mhlb
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


# 환경변수
jwt.secret.key: ${/pinme/jwt-secret-key}

workspace.default.image: ${/pinme/workspace-default-image}
user.default.image: ${/pinme/user-default-image}

aes.key: ${/pinme/aes-key}